### ISSUE TITLE
can the file descriptor leaks test ignore files in `.astropy/config`?

### ISSUE THREAD

**Issue by danielsf** [lsst/utils#31]
astropy has an option to log all warnings and exceptions to a file `.astropy/config/astropy.log`.  If users have this option enabled, then unit tests that call our `testFileDescriptorLeaks` method in `utils/tests.py` end up failing, because the handle to `astropy.log` is still open when the test cleans up.  Would it be possible to modify this test so that, if the file that is still open is `astropy.log`, the test passes.  The alternative (after having thought about it for all of 20 minutes) is to require users to turn off astropy logging when installing the stack, which doesn't seem reasonable to me.

**Comment by ktlim** [comment]
Seems like a simple PR to https://github.com/lsst/utils/blob/master/python/lsst/utils/tests.py#L171

**Comment by danielsf** [comment]
Closed by #34
